-------------------------------------------------------------СОЗДАЕМ ТАБЛИЦЫ------------------------------------------------------------
--ROLES — роли пользователей
CREATE TABLE roles (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR2(50) NOT NULL UNIQUE
);
--USERS — общие данные всех пользователей
CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(100) NOT NULL UNIQUE,
  password_hash VARCHAR2(200) NOT NULL,
  role_id NUMBER NOT NULL REFERENCES roles(role_id),
  status VARCHAR2(20) DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
--CUSTOMERS — данные покупателей
CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER REFERENCES users(user_id),
  full_name VARCHAR2(200),
  email VARCHAR2(200) UNIQUE,
  phone VARCHAR2(50),
  status VARCHAR2(20) DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
--BOOKS — каталог книг
CREATE TABLE books (
  book_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  isbn VARCHAR2(20),
  title VARCHAR2(400),
  author VARCHAR2(200),
  price NUMBER(10,2),
  stock NUMBER DEFAULT 0,
  category VARCHAR2(100),
  attributes_json CLOB CHECK (attributes_json IS JSON),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
--ORDERS — заказы покупателей
CREATE TABLE orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER REFERENCES customers(customer_id),
  order_date TIMESTAMP DEFAULT SYSTIMESTAMP,
  status VARCHAR2(50),
  total_amount NUMBER(12,2)
);
--ORDER_ITEMS — позиции заказа
CREATE TABLE order_items (
  order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER REFERENCES orders(order_id),
  book_id NUMBER REFERENCES books(book_id),
  qty NUMBER,
  price NUMBER(10,2)
);
--AUDIT_LOG — журнал действий
CREATE TABLE audit_log (
  log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  who VARCHAR2(200),
  what_table VARCHAR2(200),
  action VARCHAR2(50),
  details_json CLOB CHECK (details_json IS JSON),
  ts TIMESTAMP DEFAULT SYSTIMESTAMP
);
-------------------------------------------------------------------------------------

